### ISSUE TITLE
chown: changing ownership of '/data': Operation not permitted

### ISSUE THREAD

**Issue by basimhassan27** [marcialcv/liferayk8s#6]
search.yaml is showing this error can u please help asap 
@marcialcv 
itsbasimhassan@gmail.com is my email address

**Comment by pyoxa** [comment]
You can add this to the deployment: 
```yaml
securityContext:
  capabilities:
    add: ["SYS_CHROOT"]
```
if your ES container is running as root
